[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino
  bodmer/TFT_eSPI
build_flags =
  -D SIDEBAND_VERSION=\"0.1.0-dev\"

[env:esp32dev]
board = esp32dev

[env:ttgo-t-display]
board = ttgo-t1
build_flags =
  ${env.build_flags}
  -D SIDEBAND_HAS_TFT=1
